services:
  mint-backend:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ../../.env

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
